In [10]:
import numpy as np
import torch

DEVICE = "cpu"

In [2]:
dim = 20

matrix = np.random.random((dim, dim))

In [4]:
eigvalues, eigvectors = np.linalg.eig(matrix)

In [7]:
eigvalues

array([ 9.6930946 +0.j        ,  1.11498785+0.74235507j,
        1.11498785-0.74235507j, -1.29145067+0.j        ,
       -0.0465532 +1.11055428j, -0.0465532 -1.11055428j,
        1.11508462+0.j        ,  0.57592348+0.60789001j,
        0.57592348-0.60789001j,  0.81362575+0.j        ,
       -0.77329674+0.54685856j, -0.77329674-0.54685856j,
       -0.74664122+0.13676838j, -0.74664122-0.13676838j,
       -0.36320982+0.49743494j, -0.36320982-0.49743494j,
        0.36951896+0.23318876j,  0.36951896-0.23318876j,
       -0.16657195+0.05974004j, -0.16657195-0.05974004j])

In [9]:
eigvalues

array([ 9.6930946 +0.j        ,  1.11498785+0.74235507j,
        1.11498785-0.74235507j, -1.29145067+0.j        ,
       -0.0465532 +1.11055428j, -0.0465532 -1.11055428j,
        1.11508462+0.j        ,  0.57592348+0.60789001j,
        0.57592348-0.60789001j,  0.81362575+0.j        ,
       -0.77329674+0.54685856j, -0.77329674-0.54685856j,
       -0.74664122+0.13676838j, -0.74664122-0.13676838j,
       -0.36320982+0.49743494j, -0.36320982-0.49743494j,
        0.36951896+0.23318876j,  0.36951896-0.23318876j,
       -0.16657195+0.05974004j, -0.16657195-0.05974004j])

In [11]:
eigvalues_torch = torch.tensor(eigvalues, device=DEVICE)

In [ ]:
difference_matrix = torch.exp(-torch.abs(eigvalues_torch.unsqueeze(0) - eigvalues_torch.unsqueeze(1))**2)

In [34]:
difference_matrix

tensor([[1.0000e+00, 1.5719e+32, 1.5719e+32, 2.5239e+52, 5.4091e+41, 5.4091e+41,
         9.0441e+31, 1.8208e+36, 1.8208e+36, 1.7456e+34, 5.0678e+47, 5.0678e+47,
         2.1930e+47, 2.1930e+47, 1.0650e+44, 1.0650e+44, 5.9762e+37, 5.9762e+37,
         1.6620e+42, 1.6620e+42],
        [1.5719e+32, 1.0000e+00, 9.0645e+00, 5.6795e+02, 4.4139e+00, 1.1940e+02,
         1.7351e+00, 1.3616e+00, 8.2792e+00, 1.9001e+00, 3.6739e+01, 1.8636e+02,
         4.6173e+01, 6.9305e+01, 9.4409e+00, 4.1353e+01, 2.2591e+00, 4.5150e+00,
         8.2347e+00, 9.8331e+00],
        [1.5719e+32, 9.0645e+00, 1.0000e+00, 5.6795e+02, 1.1940e+02, 4.4139e+00,
         1.7351e+00, 8.2792e+00, 1.3616e+00, 1.9001e+00, 1.8636e+02, 3.6739e+01,
         6.9305e+01, 4.6173e+01, 4.1353e+01, 9.4409e+00, 4.5150e+00, 2.2591e+00,
         9.8331e+00, 8.2347e+00],
        [2.5239e+52, 5.6795e+02, 5.6795e+02, 1.0000e+00, 1.6169e+01, 1.6169e+01,
         3.2748e+02, 4.7305e+01, 4.7305e+01, 8.4045e+01, 1.7639e+00, 1.7639e+00,
       

In [33]:
torch.triu(difference_matrix)

tensor([[1.0000e+00, 1.5719e+32, 1.5719e+32, 2.5239e+52, 5.4091e+41, 5.4091e+41,
         9.0441e+31, 1.8208e+36, 1.8208e+36, 1.7456e+34, 5.0678e+47, 5.0678e+47,
         2.1930e+47, 2.1930e+47, 1.0650e+44, 1.0650e+44, 5.9762e+37, 5.9762e+37,
         1.6620e+42, 1.6620e+42],
        [0.0000e+00, 1.0000e+00, 9.0645e+00, 5.6795e+02, 4.4139e+00, 1.1940e+02,
         1.7351e+00, 1.3616e+00, 8.2792e+00, 1.9001e+00, 3.6739e+01, 1.8636e+02,
         4.6173e+01, 6.9305e+01, 9.4409e+00, 4.1353e+01, 2.2591e+00, 4.5150e+00,
         8.2347e+00, 9.8331e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+00, 5.6795e+02, 1.1940e+02, 4.4139e+00,
         1.7351e+00, 8.2792e+00, 1.3616e+00, 1.9001e+00, 1.8636e+02, 3.6739e+01,
         6.9305e+01, 4.6173e+01, 4.1353e+01, 9.4409e+00, 4.5150e+00, 2.2591e+00,
         9.8331e+00, 8.2347e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 1.6169e+01, 1.6169e+01,
         3.2748e+02, 4.7305e+01, 4.7305e+01, 8.4045e+01, 1.7639e+00, 1.7639e+00,
       

In [25]:
triuindex = torch.triu_indices(20, 20, offset=1)

In [29]:
triuindex.shape

torch.Size([2, 190])